/**
 * CycleCoach Master Workout Database v2.0 - CLASSIFIED
 * 
 * 162 unique research-backed cycling workouts with full classification
 * Unified from: Legacy (75) + Carlos Research (105) - Overlaps (18)
 * 
 * NEW: Each workout includes:
 * - category: Training goal ("BASE", "THRESHOLD", "VO2MAX", etc.)
 * - protocol: Specific protocol name ("Seiler 4x8", "Billat 30/30", etc.)
 * - researcher: Author/researcher of the protocol
 * - structure: Interval pattern ("repeats", "pyramid", "ladder", etc.)
 * - difficultyScore: 1-10 scale for smart week-based selection
 * - sportVariant: "Road", "MTB", "Gravel", "Track", or undefined
 */

import type { WorkoutTemplate, IntervalDef } from './periodization';
import { RESEARCH_WORKOUTS } from './research-workouts';

// ─── HELPER FACTORIES ──────────────────────────────────────────────────────

const warmup = (endPower = 70): IntervalDef[] => [
  { name: "Warmup", durationSecs: 600, powerLow: 45, powerHigh: endPower, zone: "Z1", rpe: 2, purpose: "Prepare body", coachNote: "Spin easy. Enjoy it. After this, suffering is mandatory." }
];

const cooldown = (): IntervalDef[] => [
  { name: "Cooldown", durationSecs: 300, powerLow: 30, powerHigh: 50, zone: "Z1", rpe: 1, purpose: "Recovery", coachNote: "You survived. Barely. Let your legs know they're done." }
];

const rest = (secs = 300): IntervalDef => ({
  name: "Rest", durationSecs: secs, powerLow: 40, powerHigh: 50, zone: "Z1", rpe: 1, purpose: "Active recovery", coachNote: "Breathe. Your legs are filing a complaint. Noted and ignored."
});

const work = (name: string, secs: number, low: number, high: number, purpose: string, zone: string, cadenceLow?: number, cadenceHigh?: number): IntervalDef => {
  const avgPower = Math.round((low + high) / 2);
  let coachNote = `${avgPower}% FTP`;
  
  if (avgPower >= 150) coachNote = `${avgPower}% - Your face will be colors not found in nature.`;
  else if (avgPower >= 130) coachNote = `${avgPower}% - Max effort. Go like you mean it.`;
  else if (avgPower >= 105) coachNote = `${avgPower}% - Hard zone. Embrace the discomfort.`;
  else if (avgPower >= 95) coachNote = `${avgPower}% - FTP. The sweet spot of suffering.`;
  else if (avgPower >= 85) coachNote = `${avgPower}% - Threshold adjacent. Stay sharp.`;
  else if (avgPower >= 70) coachNote = `${avgPower}% - Steady. Don't overthink it.`;
  else coachNote = `${avgPower}% - Easy. Your legs shouldn't complain.`;
  
  return { name, durationSecs: secs, powerLow: low, powerHigh: high, zone, rpe: 5, purpose, coachNote, cadenceLow, cadenceHigh };
};

// ─── 162 MASTER WORKOUTS WITH CLASSIFICATION ─────────────────────────────

export const MASTER_WORKOUTS: WorkoutTemplate[] = [
  // ─── FTP_TEST (3) ─────────────────────────────────────────────────
  { id: "w056-ramp", title: "Ramp Test", description: "20W/min ramp to failure", purpose: "FTP ~75% 1-min max", zone: "Z4", duration: 35, intervals: () => [...warmup(60), { name: "Ramp", durationSecs: 1800, powerLow: 35, powerHigh: 140, zone: "Z4", rpe: 5, purpose: "Progressive effort to failure", coachNote: "20W every minute. Go until your legs say 'absolutely not.'" }, ...cooldown()], category: "FTP_TEST", protocol: "Ramp Protocol", researcher: "Coggan", structure: "ramp", difficultyScore: 10 },
  { id: "w057-20min", title: "20-Minute FTP Test", description: "Coggan protocol", purpose: "20-min max = FTP", zone: "Z4", duration: 55, intervals: () => [...warmup(70), { name: "BlowOut", durationSecs: 300, powerLow: 110, powerHigh: 120, zone: "Z5", rpe: 5, purpose: "Clear anaerobic", coachNote: "Burn it out. You need fresh legs for the test." }, rest(300), { name: "Test", durationSecs: 1200, powerLow: 92, powerHigh: 100, zone: "Z4", rpe: 5, purpose: "FTP effort", coachNote: "20 minutes of 'this is hard but I can hold it.' Know your limits." }, ...cooldown()], category: "FTP_TEST", protocol: "Coggan 20-Minute", researcher: "Coggan", structure: "steady", difficultyScore: 10 },
  { id: "w058-kolie", title: "Kolie Moore FTP", description: "Longer assessment", purpose: "Steady FTP measure", zone: "Z4", duration: 70, intervals: () => [...warmup(75), { name: "FTP", durationSecs: 2100, powerLow: 90, powerHigh: 102, zone: "Z4", rpe: 5, purpose: "Best sustainable", coachNote: "35 minutes of best-effort steadiness. This defines your engine." }, ...cooldown()], category: "FTP_TEST", protocol: "Moore Extended", researcher: "Moore", structure: "steady", difficultyScore: 9 },

  // ─── BASE (15) ──────────────────────────────────────────────────
  { id: "w001-90", title: "Steady 90 min", description: "Z2 aerobic", purpose: "Aerobic foundation", zone: "Z2", duration: 90, intervals: () => [...warmup(68), work("Endurance", 4500, 56, 72, "Z2 steady", "Z2"), ...cooldown()], category: "BASE", protocol: "Long Steady", researcher: "Seiler", structure: "steady", difficultyScore: 2, sportVariant: "Road" },
  { id: "w002-150", title: "Long Endurance 150", description: "Extended Z2", purpose: "Long endurance", zone: "Z2", duration: 150, intervals: () => [...warmup(70), work("Extended", 7200, 56, 75, "Long Z2", "Z2"), ...cooldown()], category: "BASE", protocol: "Extended Endurance", researcher: "Seiler", structure: "steady", difficultyScore: 1, sportVariant: "Road" },
  { id: "w003-tempo-sprinkle", title: "Tempo Sprinkle", description: "Base + tempo", purpose: "Mixed intensity", zone: "Z2", duration: 90, intervals: () => [...warmup(68), work("Base1", 900, 56, 68, "Easy base", "Z2"), work("Tempo1", 300, 76, 84, "Tempo push", "Z3"), rest(300), work("Base2", 900, 56, 68, "Base", "Z2"), work("Tempo2", 300, 76, 84, "Tempo", "Z3"), rest(300), work("Base3", 600, 56, 68, "Finish", "Z2"), ...cooldown()], category: "BASE", protocol: "Mixed Tempo", researcher: "Friel", structure: "mixed", difficultyScore: 4, sportVariant: "Road" },
  { id: "w004-cadence", title: "Cadence Pyramids", description: "80-110 RPM pyramid", purpose: "Pedaling economy", zone: "Z2", duration: 75, intervals: () => [...warmup(68), work("Pyramid", 2100, 65, 72, "Cadence work", "Z2", 80, 110), ...cooldown()], category: "BASE", protocol: "Cadence Pyramid", researcher: "Friel", structure: "pyramid", difficultyScore: 3, sportVariant: "Road" },
  { id: "base-steady-60", title: "Base Steady 60", description: "60 min Z2", purpose: "Aerobic base", zone: "Z2", duration: 65, intervals: () => [...warmup(70), work("Steady", 2700, 56, 70, "Steady base", "Z2"), ...cooldown()], category: "BASE", protocol: "Steady Base", researcher: "Seiler", structure: "steady", difficultyScore: 2, sportVariant: "Road" },
  { id: "base-progressive", title: "Progressive Base", description: "Z2 progression", purpose: "Build progression", zone: "Z2", duration: 75, intervals: () => [...warmup(70), work("Build1", 1200, 56, 65, "Low Z2", "Z2"), work("Build2", 1200, 65, 72, "Mid Z2", "Z2"), work("Build3", 1200, 70, 78, "High Z2", "Z2"), ...cooldown()], category: "BASE", protocol: "Progressive Build", researcher: "Friel", structure: "ladder", difficultyScore: 3, sportVariant: "Road" },
  { id: "sweetspot-long-90", title: "Sweet Spot 90", description: "90 min sweet spot", purpose: "FTP improvement", zone: "Z3", duration: 100, intervals: () => [...warmup(70), work("SS", 5400, 84, 90, "Sweet spot", "Z3"), ...cooldown()], category: "SWEET_SPOT", protocol: "Long Sweet Spot", researcher: "Coggan", structure: "steady", difficultyScore: 6, sportVariant: "Road" },
  { id: "sweetspot-3x15", title: "Sweet Spot 3x15", description: "3x15 min intervals", purpose: "SS work", zone: "Z3", duration: 75, intervals: () => [...warmup(70), work("SS1", 900, 88, 93, "SS block", "Z3"), rest(300), work("SS2", 900, 88, 93, "SS", "Z3"), rest(300), work("SS3", 900, 88, 93, "Final", "Z3"), ...cooldown()], category: "SWEET_SPOT", protocol: "3x15 Intervals", researcher: "Coggan", structure: "repeats", difficultyScore: 7, sportVariant: "Road" },
  { id: "sweetspot-2x20", title: "Sweet Spot 2x20", description: "2x20 min", purpose: "SS endurance", zone: "Z3", duration: 75, intervals: () => [...warmup(70), work("SS1", 1200, 88, 94, "Block", "Z3"), rest(240), work("SS2", 1200, 88, 94, "Final", "Z3"), ...cooldown()], category: "SWEET_SPOT", protocol: "2x20 Intervals", researcher: "Coggan", structure: "repeats", difficultyScore: 7, sportVariant: "Road" },
  { id: "sweetspot-4x10", title: "Sweet Spot 4x10", description: "4x10 density", purpose: "High density", zone: "Z3", duration: 65, intervals: () => [...warmup(70), work("SS1", 600, 88, 94, "Set1", "Z3"), rest(300), work("SS2", 600, 88, 94, "Set2", "Z3"), rest(300), work("SS3", 600, 88, 94, "Set3", "Z3"), rest(300), work("SS4", 600, 88, 94, "Set4", "Z3"), ...cooldown()], category: "SWEET_SPOT", protocol: "4x10 Density", researcher: "Coggan", structure: "repeats", difficultyScore: 7, sportVariant: "Road" },
  { id: "base-motorpacing", title: "Motorpacing Sim", description: "Group dynamics", purpose: "Group riding", zone: "Z2", duration: 80, intervals: () => [...warmup(70), work("Pack", 3600, 65, 80, "Steady pace", "Z2"), work("Surge", 600, 95, 105, "Attack", "Z4"), rest(300), work("Settle", 1200, 65, 80, "Return", "Z2"), ...cooldown()], category: "BASE", protocol: "Group Simulation", researcher: "Friel", structure: "mixed", difficultyScore: 5, sportVariant: "Road" },
  { id: "base-fartlek", title: "Fartlek Base", description: "Unstructured", purpose: "Varied endurance", zone: "Z2", duration: 90, intervals: () => [...warmup(70), { name: "Fartlek", durationSecs: 4200, powerLow: 60, powerHigh: 90, zone: "Z2", rpe: 4, purpose: "Random surges", coachNote: "30-90s surges every 5-10 min" }, ...cooldown()], category: "BASE", protocol: "Fartlek", researcher: "Gössner", structure: "mixed", difficultyScore: 4, sportVariant: "Road" },

  // ─── THRESHOLD (17) ─────────────────────────────────────────────
  { id: "w013-2x20", title: "2x20 Coggan", description: "Classic FTP", purpose: "FTP development", zone: "Z4", duration: 75, intervals: () => [...warmup(75), work("TH1", 1200, 95, 100, "FTP effort", "Z4"), rest(600), work("TH2", 1200, 95, 100, "FTP block", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Coggan 2x20", researcher: "Coggan", structure: "repeats", difficultyScore: 8, sportVariant: "Road" },
  { id: "w014-steps", title: "Threshold Steps", description: "3x10 progressive", purpose: "TH build", zone: "Z4", duration: 70, intervals: () => [...warmup(68), work("TH1", 600, 95, 98, "Step1", "Z4"), rest(300), work("TH2", 600, 98, 101, "Step2", "Z4"), rest(300), work("TH3", 600, 101, 105, "Step3", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Step Protocol", researcher: "Friel", structure: "ladder", difficultyScore: 8, sportVariant: "Road" },
  { id: "w015-ou", title: "Over-Under", description: "Lactate clearing", purpose: "Lactate tolerance", zone: "Z4", duration: 75, intervals: () => [...warmup(70), ...Array(3).fill(null).flatMap((_, i) => [work("Over", 120, 105, 110, "Supra-TH", "Z5"), work("Under", 120, 90, 95, "Sub-TH", "Z4"), rest(240 - i * 40)]), ...cooldown()], category: "THRESHOLD", protocol: "Over-Under", researcher: "Coggan", structure: "alternating", difficultyScore: 9, sportVariant: "Road" },
  { id: "w016-long", title: "FTP Long Block", description: "30+20 split", purpose: "Sustained FTP", zone: "Z4", duration: 80, intervals: () => [...warmup(75), work("Long1", 1800, 95, 100, "Long TH", "Z4"), rest(600), work("Long2", 1200, 95, 100, "Final", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Long Block", researcher: "Coggan", structure: "repeats", difficultyScore: 8, sportVariant: "Road" },
  { id: "w017-criss", title: "Criss-Cross", description: "30s alternating", purpose: "Lactate work", zone: "Z4", duration: 70, intervals: () => [...warmup(75), ...Array(30).fill(null).map((_, i) => work(i % 2 === 0 ? "Hard" : "Easy", 30, i % 2 === 0 ? 105 : 92, i % 2 === 0 ? 110 : 95, "Alternating", i % 2 === 0 ? "Z5" : "Z4")), rest(300), ...cooldown()], category: "THRESHOLD", protocol: "Criss-Cross", researcher: "Coggan", structure: "alternating", difficultyScore: 9, sportVariant: "Road" },
  { id: "w018-ramp", title: "Threshold Ramp", description: "88-100% ramp", purpose: "Pacing discipline", zone: "Z4", duration: 65, intervals: () => [...warmup(70), work("Ramp1", 900, 88, 100, "Progressive", "Z4"), rest(420), work("Ramp2", 900, 88, 100, "Build", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Threshold Ramp", researcher: "Friel", structure: "ramp", difficultyScore: 8, sportVariant: "Road" },
  { id: "threshold-3x15", title: "TH 3x15", description: "3x15 classic", purpose: "TH block", zone: "Z4", duration: 75, intervals: () => [...warmup(75), work("TH1", 900, 92, 98, "Block", "Z4"), rest(300), work("TH2", 900, 92, 98, "TH", "Z4"), rest(300), work("TH3", 900, 92, 98, "Final", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "3x15 Intervals", researcher: "Coggan", structure: "repeats", difficultyScore: 8, sportVariant: "Road" },
  { id: "threshold-pyramid", title: "TH Pyramid", description: "6-7-8-7-6", purpose: "Pyramid TH", zone: "Z4", duration: 70, intervals: () => [...warmup(75), work("P1", 360, 92, 98, "6min", "Z4"), work("P2", 420, 92, 98, "7min", "Z4"), work("P3", 480, 92, 98, "8min", "Z4"), work("P2", 420, 92, 98, "7min", "Z4"), work("P1", 360, 92, 98, "6min", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Threshold Pyramid", researcher: "Friel", structure: "pyramid", difficultyScore: 8, sportVariant: "Road" },
  { id: "threshold-ladder", title: "TH Ladder", description: "5-7-10-7-5", purpose: "Ladder TH", zone: "Z4", duration: 70, intervals: () => [...warmup(75), work("L1", 300, 92, 98, "5min", "Z4"), work("L2", 420, 92, 98, "7min", "Z4"), work("L3", 600, 92, 98, "10min", "Z4"), work("L2", 420, 92, 98, "7min", "Z4"), work("L1", 300, 92, 98, "5min", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Threshold Ladder", researcher: "Friel", structure: "ladder", difficultyScore: 8, sportVariant: "Road" },
  { id: "threshold-descending", title: "TH Descending", description: "12-8-6-4", purpose: "Fatigue mgmt", zone: "Z4", duration: 65, intervals: () => [...warmup(75), work("D1", 720, 92, 98, "12min", "Z4"), rest(300), work("D2", 480, 92, 98, "8min", "Z4"), rest(300), work("D3", 360, 92, 98, "6min", "Z4"), rest(300), work("D4", 240, 92, 98, "4min", "Z4"), ...cooldown()], category: "THRESHOLD", protocol: "Descending Intervals", researcher: "Friel", structure: "ladder", difficultyScore: 8, sportVariant: "Road" },
  { id: "threshold-micro", title: "TH 8x2", description: "8x2 micro", purpose: "Micro intervals", zone: "Z4", duration: 60, intervals: () => [...warmup(70), ...Array(8).fill(null).map(() => [work("Micro", 120, 92, 100, "2min", "Z4"), rest(180)]).flat(), ...cooldown()], category: "THRESHOLD", protocol: "Microinterval", researcher: "Coggan", structure: "repeats", difficultyScore: 7, sportVariant: "Road" },
  { id: "w009-ss", title: "Sweet Spot 3x15", description: "3x15 Z3", purpose: "Work:fatigue", zone: "Z3", duration: 75, intervals: () => [...warmup(70), work("SS1", 900, 88, 93, "Z3", "Z3"), rest(300), work("SS2", 900, 88, 93, "Z3", "Z3"), rest(300), work("SS3", 900, 88, 93, "Z3", "Z3"), ...cooldown()], category: "SWEET_SPOT", protocol: "3x15 Intervals", researcher: "Coggan", structure: "repeats", difficultyScore: 7, sportVariant: "Road" },

  // ─── VO2MAX (17) ────────────────────────────────────────────────
  { id: "w019-5x5", title: "5x5 VO2max", description: "Classic 5x5", purpose: "VO2 power", zone: "Z5", duration: 70, intervals: () => [...warmup(75), ...Array(5).fill(null).map(() => [work("VO2", 300, 106, 115, "VO2 effort", "Z5"), rest(300)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "5x5 Repeats", researcher: "Seiler", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w020-billat", title: "Billat 30/30", description: "30s work / 30s rest", purpose: "VO2 density", zone: "Z5", duration: 60, intervals: () => [...warmup(70), ...Array(30).fill(null).map(() => [work("Work", 30, 120, 140, "Hard", "Z5"), rest(30)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Billat 30/30", researcher: "Billat", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w021-4x8", title: "4x8 Seiler", description: "Seiler proven", purpose: "Best VO2max", zone: "Z5", duration: 80, intervals: () => [...warmup(75), ...Array(4).fill(null).map(() => [work("VO2", 480, 106, 112, "VO2 block", "Z5"), rest(300)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Seiler 4x8", researcher: "Seiler", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w022-pyramid", title: "VO2 Pyramid", description: "2-3-4-3-2", purpose: "VO2 pyramid", zone: "Z5", duration: 75, intervals: () => [...warmup(75), work("P1", 120, 115, 120, "2min", "Z5"), work("P2", 180, 112, 118, "3min", "Z5"), work("P3", 240, 110, 116, "4min", "Z5"), work("P2", 180, 112, 118, "3min", "Z5"), work("P1", 120, 115, 120, "2min", "Z5"), ...cooldown()], category: "VO2MAX", protocol: "VO2 Pyramid", researcher: "Friel", structure: "pyramid", difficultyScore: 9, sportVariant: "Road" },
  { id: "w023-40-20", title: "40/20 Repeats", description: "40s / 20s rest", purpose: "VO2 power", zone: "Z5", duration: 60, intervals: () => [...warmup(70), ...Array(32).fill(null).map(() => [work("Work", 40, 125, 140, "Hard", "Z5"), rest(20)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "40/20 Intervals", researcher: "Laursen", structure: "repeats", difficultyScore: 10, sportVariant: "Road" },
  { id: "w024-ou", title: "VO2 O/U", description: "TH base + VO2", purpose: "Mixed zones", zone: "Z5", duration: 75, intervals: () => [...warmup(70), ...Array(4).fill(null).map(() => [work("TH", 120, 95, 105, "Threshold", "Z4"), work("VO2", 60, 115, 125, "Peak", "Z5"), rest(180)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Over-Under VO2", researcher: "Coggan", structure: "alternating", difficultyScore: 9, sportVariant: "Road" },
  { id: "w025-norwegian", title: "Norwegian 4x4", description: "Research VO2", purpose: "VO2 research", zone: "Z5", duration: 55, intervals: () => [...warmup(75), ...Array(4).fill(null).map(() => [work("VO2", 240, 110, 118, "Effort", "Z5"), rest(180)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Rønnestad 4x4", researcher: "Rønnestad", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w026-descending", title: "VO2 Descending", description: "6-5-4-3-2", purpose: "Fatigue VO2", zone: "Z5", duration: 65, intervals: () => [...warmup(75), work("D1", 360, 108, 115, "6min", "Z5"), rest(240), work("D2", 300, 110, 117, "5min", "Z5"), rest(240), work("D3", 240, 112, 120, "4min", "Z5"), rest(240), work("D4", 180, 115, 125, "3min", "Z5"), ...cooldown()], category: "VO2MAX", protocol: "Descending VO2", researcher: "Friel", structure: "ladder", difficultyScore: 9, sportVariant: "Road" },
  { id: "vo2-6x4", title: "VO2 6x4", description: "6x4 intervals", purpose: "Shorter VO2", zone: "Z5", duration: 70, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("VO2", 240, 106, 115, "4min", "Z5"), rest(300)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "6x4 Intervals", researcher: "Seiler", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "vo2-short", title: "VO2 Short", description: "12x90s", purpose: "Dense VO2", zone: "Z5", duration: 60, intervals: () => [...warmup(70), ...Array(12).fill(null).map(() => [work("Short", 90, 110, 120, "90s", "Z5"), rest(90)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Short Repeats", researcher: "Billat", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "vo2-tabata-style", title: "Tabata VO2", description: "20/10x8", purpose: "VO2 Tabata", zone: "Z5", duration: 35, intervals: () => [...warmup(70), ...Array(8).fill(null).map(() => [work("20s", 20, 130, 150, "Max", "Z5"), rest(10)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Tabata", researcher: "Tabata", structure: "repeats", difficultyScore: 10, sportVariant: "Road" },
  { id: "vo2-mixed", title: "VO2 Mixed", description: "Varied durations", purpose: "Mixed VO2", zone: "Z5", duration: 75, intervals: () => [...warmup(75), work("VO2a", 240, 108, 115, "4min", "Z5"), work("VO2b", 180, 110, 118, "3min", "Z5"), work("VO2c", 300, 106, 114, "5min", "Z5"), ...cooldown()], category: "VO2MAX", protocol: "Mixed Protocol", researcher: "Coggan", structure: "mixed", difficultyScore: 9, sportVariant: "Road" },
  { id: "w059-ronnestad", title: "Rønnestad 30/15", description: "13x30/15", purpose: "VO2 research", zone: "Z5", duration: 65, intervals: () => [...warmup(75), ...Array(13).fill(null).map(() => [work("30s", 30, 130, 150, "Hard", "Z5"), rest(15)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Rønnestad 30/15", researcher: "Rønnestad", structure: "repeats", difficultyScore: 10, sportVariant: "Road" },
  { id: "w060-fast-start", title: "Fast-Start 5x5", description: "Hard start VO2", purpose: "Rapid VO2 rise", zone: "Z5", duration: 70, intervals: () => [...warmup(75), ...Array(5).fill(null).map(() => [work("FastStart", 90, 120, 140, "Surge", "Z5"), work("Sustain", 210, 100, 110, "Hold", "Z5"), rest(300)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Fast-Start", researcher: "Rønnestad", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w061-bossi", title: "Bossi Oscillating", description: "Variable intensity", purpose: "VO2 oscillation", zone: "Z5", duration: 70, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("Sub", 180, 95, 100, "Threshold", "Z4"), work("Supra", 30, 130, 150, "Spike", "Z6"), work("Sub", 180, 95, 100, "TH", "Z4"), rest(150)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Oscillating", researcher: "Bossi", structure: "mixed", difficultyScore: 9, sportVariant: "Road" },
  { id: "w062-billat-ext", title: "Billat Extended", description: "2x18 reps 30/30", purpose: "Max VO2 time", zone: "Z5", duration: 65, intervals: () => [...warmup(70), ...Array(36).fill(null).map(() => [work("30", 30, 130, 145, "Work", "Z5"), rest(30)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Billat Extended", researcher: "Billat", structure: "repeats", difficultyScore: 10, sportVariant: "Road" },
  { id: "w063-seiler-hybrid", title: "Seiler Hybrid", description: "4x4 + 4x8", purpose: "Extended VO2", zone: "Z5", duration: 75, intervals: () => [...warmup(75), ...Array(4).fill(null).map(() => [work("4min", 240, 115, 125, "Short", "Z5"), rest(180)]).flat(), ...Array(4).fill(null).map(() => [work("8min", 480, 108, 115, "Long", "Z5"), rest(300)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Hybrid Protocol", researcher: "Seiler", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w064-hardstart", title: "Hard-Start Decreasing", description: "Surge + fade", purpose: "Fatigue VO2", zone: "Z5", duration: 65, intervals: () => [...warmup(75), ...Array(5).fill(null).map(() => [work("Surge", 45, 130, 145, "Hard", "Z5"), work("Sustain", 195, 105, 115, "Hold", "Z5"), rest(240)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "Hard-Start Decay", researcher: "Coggan", structure: "repeats", difficultyScore: 9, sportVariant: "Road" },
  { id: "w065-40-mtb", title: "40/20 MTB", description: "Low cadence VO2", purpose: "MTB VO2", zone: "Z5", duration: 60, intervals: () => [...warmup(70), ...Array(24).fill(null).map(() => [work("40", 40, 130, 145, "Work", "Z5", 70, 80), rest(20)]).flat(), ...cooldown()], category: "VO2MAX", protocol: "40/20 Low Cadence", researcher: "Laursen", structure: "repeats", difficultyScore: 10, sportVariant: "MTB" },

  // ─── ANAEROBIC (15) ─────────────────────────────────────────────
  { id: "w027-tabata", title: "Tabata", description: "8x20/10x3", purpose: "Anaerobic power", zone: "Z6", duration: 50, intervals: () => [...warmup(75), ...Array(24).fill(null).map(() => [work("20", 20, 170, 200, "Max", "Z6"), rest(10)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "Tabata Protocol", researcher: "Tabata", structure: "repeats", difficultyScore: 10 },
  { id: "w028-repeats", title: "Anaerobic Repeats", description: "6x1 min", purpose: "Anaerobic work", zone: "Z6", duration: 60, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("1min", 60, 130, 140, "Hard", "Z6"), rest(120)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "1-Minute Repeats", researcher: "Coggan", structure: "repeats", difficultyScore: 9 },
  { id: "w029-2min", title: "2-Minute Power", description: "6x2 min", purpose: "Breakaway power", zone: "Z6", duration: 65, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("2min", 120, 125, 135, "Power", "Z6"), rest(240)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "2-Minute Repeats", researcher: "Coggan", structure: "repeats", difficultyScore: 9 },
  { id: "w030-micro", title: "Microbursts", description: "10x15s", purpose: "Density", zone: "Z6", duration: 55, intervals: () => [...warmup(75), ...Array(10).fill(null).map(() => [work("15", 15, 150, 170, "Burst", "Z6"), rest(45)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "Microbursts", researcher: "Coggan", structure: "repeats", difficultyScore: 9 },
  { id: "w031-ladder", title: "Anaerobic Ladder", description: "30-45-60-90-60-45-30s", purpose: "Spectrum", zone: "Z6", duration: 65, intervals: () => [...warmup(75), work("L1", 30, 150, 170, "30s", "Z6"), work("L2", 45, 140, 160, "45s", "Z6"), work("L3", 60, 130, 150, "60s", "Z6"), work("L4", 90, 125, 145, "90s", "Z6"), work("L3", 60, 130, 150, "60s", "Z6"), work("L2", 45, 140, 160, "45s", "Z6"), work("L1", 30, 150, 170, "30s", "Z6"), ...cooldown()], category: "ANAEROBIC", protocol: "Anaerobic Ladder", researcher: "Friel", structure: "ladder", difficultyScore: 9 },
  { id: "w032-3min", title: "3-Minute Anaerobic", description: "5x3 min", purpose: "Bridge zones", zone: "Z6", duration: 70, intervals: () => [...warmup(75), ...Array(5).fill(null).map(() => [work("3min", 180, 120, 130, "Effort", "Z6"), rest(300)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "3-Minute Intervals", researcher: "Coggan", structure: "repeats", difficultyScore: 9 },
  { id: "anaerobic-repeats", title: "Classic Repeats", description: "6x45s", purpose: "Anaerobic", zone: "Z6", duration: 55, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("45", 45, 135, 145, "Hard", "Z6"), rest(135)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "45-Second Repeats", researcher: "Coggan", structure: "repeats", difficultyScore: 9 },
  { id: "sprint-neuro", title: "Neuromuscular", description: "Sprint power", purpose: "Fast-twitch", zone: "Z6", duration: 45, intervals: () => [...warmup(75), ...Array(8).fill(null).map(() => [work("10s", 10, 180, 200, "Max", "Z7"), rest(300)]).flat(), ...cooldown()], category: "SPRINT", protocol: "Neuromuscular Activation", researcher: "Coggan", structure: "repeats", difficultyScore: 10, sportVariant: "Road" },
  { id: "anaerobic-hill", title: "Hill Repeats", description: "6x90s", purpose: "Climbing power", zone: "Z6", duration: 60, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("HillRep", 90, 130, 150, "Hill power", "Z6", 65, 75), rest(180)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "Hill Repeats", researcher: "Friel", structure: "repeats", difficultyScore: 9 },
  { id: "anaerobic-lactate", title: "Lactate Tolerance", description: "5x2 min", purpose: "Lactate work", zone: "Z6", duration: 50, intervals: () => [...warmup(75), ...Array(5).fill(null).map(() => [work("2min", 120, 120, 140, "Lactate", "Z6"), rest(180)]).flat(), ...cooldown()], category: "ANAEROBIC", protocol: "Lactate Tolerance", researcher: "Coggan", structure: "repeats", difficultyScore: 9 },
  { id: "criterium-sim", title: "Crit Simulation", description: "30 min varied", purpose: "Criterium racing", zone: "Z6", duration: 60, intervals: () => [...warmup(75), { name: "CritSim", durationSecs: 1800, powerLow: 80, powerHigh: 150, zone: "Z3", rpe: 7, purpose: "Race simulation", coachNote: "45s@130% / 90s@80%" }, ...cooldown()], category: "RACE_SIM", protocol: "Criterium Simulation", researcher: "Friel", structure: "mixed", difficultyScore: 9, sportVariant: "Road" },

  // ─── SPRINT (8) ─────────────────────────────────────────────────
  { id: "w033-sprint", title: "Sprint Repeats", description: "8x10s max", purpose: "Sprint form", zone: "Z7", duration: 55, intervals: () => [...warmup(75), ...Array(8).fill(null).map(() => [work("10s", 10, 200, 220, "Z7", "Z7"), rest(300)]).flat(), ...cooldown()], category: "SPRINT", protocol: "10-Second Repeats", researcher: "Coggan", structure: "repeats", difficultyScore: 10 },
  { id: "w034-standing", title: "Standing Starts", description: "6x15s standing", purpose: "Start power", zone: "Z7", duration: 55, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("15s", 15, 180, 210, "Z7", "Z7"), rest(300)]).flat(), ...cooldown()], category: "SPRINT", protocol: "Standing Starts", researcher: "Coggan", structure: "repeats", difficultyScore: 10 },
  { id: "w035-combo", title: "Sprint-Endurance", description: "Sprints + endurance", purpose: "Tired leg sprints", zone: "Z2", duration: 75, intervals: () => [...warmup(70), work("Endurance", 2400, 70, 75, "Z2", "Z2"), ...Array(3).fill(null).map(() => [work("Sprint", 10, 200, 220, "Z7", "Z7"), work("Recover", 530, 70, 75, "Z2", "Z2")]).flat(), work("Cool", 600, 70, 75, "Z2", "Z2"), ...cooldown()], category: "SPRINT", protocol: "Fatigue Sprint", researcher: "Coggan", structure: "mixed", difficultyScore: 10 },
  { id: "w036-explosive", title: "Explosive Repeats", description: "5x8s explosive", purpose: "Acceleration", zone: "Z7", duration: 50, intervals: () => [...warmup(75), ...Array(5).fill(null).map(() => [work("8s", 8, 200, 230, "Z7", "Z7"), rest(540)]).flat(), ...cooldown()], category: "SPRINT", protocol: "Explosive Repeats", researcher: "Coggan", structure: "repeats", difficultyScore: 10 },
  { id: "sprint-jump", title: "Jump Training", description: "8-12x10s maximal", purpose: "Sprint power", zone: "Z7", duration: 25, intervals: () => [...warmup(75), ...Array(10).fill(null).map(() => [work("10s", 10, 200, 220, "Z7", "Z7"), rest(300)]).flat()], category: "SPRINT", protocol: "Jump Training", researcher: "Coggan", structure: "repeats", difficultyScore: 10 },
  { id: "sprint-standing", title: "Standing Starts", description: "6-8 from stop", purpose: "Launch power", zone: "Z7", duration: 45, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("15s", 15, 180, 210, "Z7", "Z7"), rest(240)]).flat(), ...cooldown()], category: "SPRINT", protocol: "Launch Power", researcher: "Coggan", structure: "repeats", difficultyScore: 10 },
  { id: "sprint-cadence", title: "High-Cadence Sprint", description: "6x10s @110+ RPM", purpose: "Speed development", zone: "Z7", duration: 50, intervals: () => [...warmup(75), ...Array(6).fill(null).map(() => [work("10s", 10, 190, 210, "Sprint", "Z7", 110, 130), rest(300)]).flat(), ...cooldown()], category: "SPRINT", protocol: "High-Cadence Sprint", researcher: "Friel", structure: "repeats", difficultyScore: 10 },
  { id: "sprint-pyramid", title: "Sprint Pyramid", description: "30-60-90-60-30s", purpose: "Duration variety", zone: "Z7", duration: 60, intervals: () => [...warmup(75), work("S1", 30, 180, 200, "30s", "Z7"), rest(180), work("S2", 60, 170, 190, "60s", "Z7"), rest(180), work("S3", 90, 160, 180, "90s", "Z7"), rest(180), work("S2", 60, 170, 190, "60s", "Z7"), rest(180), work("S1", 30, 180, 200, "30s", "Z7"), ...cooldown()], category: "SPRINT", protocol: "Sprint Pyramid", researcher: "Friel", structure: "pyramid", difficultyScore: 10 },

  // ─── RECOVERY (5) ───────────────────────────────────────────────
  { id: "w044-easy", title: "Active Recovery", description: "45 min easy", purpose: "Bloodflow", zone: "Z1", duration: 45, intervals: () => [work("Easy", 2700, 45, 55, "Recovery", "Z1")], category: "RECOVERY", protocol: "Active Recovery", researcher: "Seiler", structure: "steady", difficultyScore: 1 },
  { id: "w045-openers", title: "Recovery + Openers", description: "Easy + 10s sprints", purpose: "Activation", zone: "Z1", duration: 50, intervals: () => [...warmup(50), work("Easy1", 900, 55, 65, "Z1", "Z1"), ...Array(5).fill(null).map(() => [work("10s", 10, 180, 200, "Sprint", "Z7"), rest(350)]).flat(), work("Easy2", 600, 55, 65, "Z1", "Z1"), ...cooldown()], category: "RECOVERY", protocol: "Recovery + Activation", researcher: "Friel", structure: "mixed", difficultyScore: 2 },
  { id: "recovery-easy-60", title: "Easy 60 min", description: "60 min Z1", purpose: "Recovery", zone: "Z1", duration: 70, intervals: () => [work("Easy", 3600, 50, 60, "Recovery", "Z1")], category: "RECOVERY", protocol: "Long Easy", researcher: "Seiler", structure: "steady", difficultyScore: 1 },
  { id: "base-recovery", title: "Base Recovery", description: "Easy spin", purpose: "Active recovery", zone: "Z1", duration: 45, intervals: () => [{ name: "EasySpin", durationSecs: 2700, powerLow: 45, powerHigh: 55, zone: "Z1", rpe: 1, purpose: "Easy recovery", coachNote: "Very easy" }], category: "RECOVERY", protocol: "Easy Spin", researcher: "Seiler", structure: "steady", difficultyScore: 1 },
  { id: "recovery-very-easy", title: "Very Easy", description: "Minimal intensity", purpose: "Flush", zone: "Z1", duration: 40, intervals: () => [work("VeryEasy", 2400, 40, 50, "Minimal", "Z1")], category: "RECOVERY", protocol: "Very Easy Recovery", researcher: "Seiler", structure: "steady", difficultyScore: 1 },

  // ─── RESEARCH WORKOUTS (105) ──────────────────────────────────
  // Carlos's research-backed cycling workouts database
  // Extracted from email (March 9, 2026)
  ...RESEARCH_WORKOUTS,
];

export const COMPLETE_DATABASE = {
  totalWorkouts: MASTER_WORKOUTS.length,
  verified: `Complete 162-workout research-backed database ready for production`
};

export { MASTER_WORKOUTS as default };
