/**
 * ZWIFT WORKOUTS - Complete 77 Unique Sessions
 * Extracted from Zwift Labs Catalog (March 10, 2026)
 * All structured with percentage-based durations for auto-scaling
 * 
 * Categories:
 * - Standalone Icons (19)
 * - Build Me Up Series (36) - includes Unicorn progression
 * - FTP Builder Series (16)
 * - Crit Crusher Series (6)
 */

import type { WorkoutTemplate } from './periodization';

export const ZWIFT_WORKOUTS: WorkoutTemplate[] = [
  // ─── STANDALONE ICONS (19) ──────────────────────────────────────
  
  {
    id: 'zw01_gorby',
    title: 'The Gorby',
    category: 'VO2MAX',
    description: '10m warm + 5×5m @110% / 5m @55% + cool',
    purpose: 'VO2max intervals',
    zone: 'Z1-Z5',
    duration: 60,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 45, powerHigh: 70, zone: 'Z1', rpe: 2, purpose: 'Warm up', coachNote: 'Easy progressive spin' },
      { name: 'VO2 Work', durationPercent: 80, powerLow: 110, powerHigh: 120, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: '5×5min at 110% FTP, 5min recovery' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 30, powerHigh: 50, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy spinning' },
    ],
    protocol: 'Zwift - The Gorby',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },
  
  {
    id: 'zw02_wringer',
    title: 'The Wringer',
    category: 'ANAEROBIC',
    description: '12m warm + 12×30s @200-205% + cool',
    purpose: 'Anaerobic power',
    zone: 'Z1-Z6',
    duration: 45,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 45, powerHigh: 70, zone: 'Z1', rpe: 2, purpose: 'Warm up', coachNote: 'Get the legs loose' },
      { name: 'Sprints', durationPercent: 80, powerLow: 200, powerHigh: 210, zone: 'Z6', rpe: 9, purpose: 'Anaerobic', coachNote: '12×30s max effort sprints' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 30, powerHigh: 50, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy recovery' },
    ],
    protocol: 'Zwift - The Wringer',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw03_mccarthy',
    title: 'McCarthy Special',
    category: 'THRESHOLD',
    description: 'Varied threshold intervals',
    purpose: 'Threshold work',
    zone: 'Z4',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Progressive build' },
      { name: 'Threshold', durationPercent: 80, powerLow: 95, powerHigh: 105, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Sustained FTP effort' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Flush the system' },
    ],
    protocol: 'Zwift - McCarthy',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw04_sst1',
    title: 'SST Tier 1',
    category: 'SWEET_SPOT',
    description: 'Sweet spot intervals - Tier 1',
    purpose: 'Sweet spot',
    zone: 'Z3',
    duration: 60,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Easy spin' },
      { name: 'Sweet Spot', durationPercent: 80, powerLow: 88, powerHigh: 93, zone: 'Z3', rpe: 7, purpose: 'Sweet spot', coachNote: 'Sustained at 88-93% FTP' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Spin easy' },
    ],
    protocol: 'Zwift - SST Tier 1',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw05_sst2',
    title: 'SST Tier 2',
    category: 'SWEET_SPOT',
    description: 'Extended sweet spot - Tier 2',
    purpose: 'Sweet spot endurance',
    zone: 'Z3',
    duration: 75,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build gradually' },
      { name: 'Sweet Spot Block', durationPercent: 82, powerLow: 88, powerHigh: 93, zone: 'Z3', rpe: 7, purpose: 'SS endurance', coachNote: 'Longer sustained sweet spot' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery spin' },
    ],
    protocol: 'Zwift - SST Tier 2',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw06_over_under',
    title: 'Over-Under Threshold',
    category: 'THRESHOLD',
    description: '110% / 90% alternating',
    purpose: 'Threshold dynamics',
    zone: 'Z4-Z5',
    duration: 60,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare system' },
      { name: 'Over-Under', durationPercent: 80, powerLow: 90, powerHigh: 110, zone: 'Z4-Z5', rpe: 8, purpose: 'Threshold', coachNote: 'Alternate above/below FTP' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Over-Under',
    researcher: 'Zwift Labs',
    structure: 'alternating',
  },

  {
    id: 'zw07_40_20',
    title: '40/20 Repeats',
    category: 'VO2MAX',
    description: '40s hard / 20s easy repeats',
    purpose: 'VO2max power',
    zone: 'Z5-Z6',
    duration: 45,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Get ready' },
      { name: '40/20s', durationPercent: 80, powerLow: 120, powerHigh: 140, zone: 'Z5-Z6', rpe: 9, purpose: 'VO2max', coachNote: '40s hard, 20s easy repeats' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Finish easy' },
    ],
    protocol: 'Zwift - 40/20',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw08_30_30',
    title: '30/30 Efforts',
    category: 'VO2MAX',
    description: '30s hard / 30s easy intervals',
    purpose: 'VO2max capacity',
    zone: 'Z5',
    duration: 45,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: '30/30s', durationPercent: 80, powerLow: 110, powerHigh: 130, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: '30s hard, 30s recovery repeats' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy spin' },
    ],
    protocol: 'Zwift - 30/30',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw09_ramp_test',
    title: 'Ramp Test',
    category: 'FTP_TEST',
    description: '20W/min ramp to failure',
    purpose: 'FTP assessment',
    zone: 'Z1-Z6',
    duration: 45,
    difficultyScore: 10,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Get ready for max effort' },
      { name: 'Ramp', durationPercent: 80, powerLow: 35, powerHigh: 140, zone: 'Z1-Z6', rpe: 10, purpose: 'FTP test', coachNote: 'Go to failure - 20W every minute' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 30, powerHigh: 50, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy recovery' },
    ],
    protocol: 'Zwift - Ramp Test',
    researcher: 'Zwift Labs',
    structure: 'ramp',
  },

  {
    id: 'zw10_ftp_20min',
    title: 'FTP Test 20-Minute',
    category: 'FTP_TEST',
    description: '20-minute all-out FTP test',
    purpose: 'FTP determination',
    zone: 'Z4',
    duration: 55,
    difficultyScore: 10,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 80, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare for effort' },
      { name: 'FTP Test', durationPercent: 80, powerLow: 92, powerHigh: 100, zone: 'Z4', rpe: 10, purpose: 'FTP', coachNote: '20 minutes at best effort' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - FTP 20min',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw11_5x8_ftp',
    title: '5×8 FTP',
    category: 'THRESHOLD',
    description: '5 repeats of 8 minutes at FTP',
    purpose: 'Threshold repeats',
    zone: 'Z4',
    duration: 70,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'FTP Repeats', durationPercent: 82, powerLow: 95, powerHigh: 105, zone: 'Z4', rpe: 8, purpose: 'FTP', coachNote: '5×8min at FTP with rest' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - 5×8 FTP',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw12_3x12_threshold',
    title: '3×12 Threshold',
    category: 'THRESHOLD',
    description: '3 repeats of 12 minutes at threshold',
    purpose: 'Long threshold',
    zone: 'Z4',
    duration: 75,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build up' },
      { name: 'Threshold', durationPercent: 82, powerLow: 95, powerHigh: 105, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: '3×12min blocks' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy spin' },
    ],
    protocol: 'Zwift - 3×12',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw13_threshold_pyramid',
    title: 'Threshold Pyramid',
    category: 'THRESHOLD',
    description: 'Pyramid threshold work',
    purpose: 'Threshold pyramid',
    zone: 'Z4',
    duration: 70,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Pyramid', durationPercent: 82, powerLow: 95, powerHigh: 105, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Ascending/descending threshold efforts' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Pyramid',
    researcher: 'Zwift Labs',
    structure: 'pyramid',
  },

  {
    id: 'zw14_microbursts',
    title: 'Microbursts',
    category: 'ANAEROBIC',
    description: 'Short hard efforts within Z2',
    purpose: 'Neuromuscular',
    zone: 'Z2-Z5',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Easy start' },
      { name: 'Microbursts', durationPercent: 80, powerLow: 60, powerHigh: 130, zone: 'Z2-Z5', rpe: 7, purpose: 'Neuro', coachNote: 'Short power bursts in endurance' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Microbursts',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw15_long_endurance',
    title: 'Long Endurance',
    category: 'BASE',
    description: 'Extended Z2 endurance work',
    purpose: 'Aerobic base',
    zone: 'Z2',
    duration: 120,
    difficultyScore: 2,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 65, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Easy start' },
      { name: 'Steady Z2', durationPercent: 82, powerLow: 55, powerHigh: 75, zone: 'Z2', rpe: 4, purpose: 'Endurance', coachNote: 'Long steady effort' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Long Endurance',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw16_recovery_spin',
    title: 'Recovery Spin',
    category: 'RECOVERY',
    description: 'Easy Z1 recovery spinning',
    purpose: 'Active recovery',
    zone: 'Z1',
    duration: 45,
    difficultyScore: 1,
    intervals: () => [
      { name: 'Easy Spin', durationPercent: 100, powerLow: 30, powerHigh: 50, zone: 'Z1', rpe: 1, purpose: 'Recovery', coachNote: 'Just spin easy and recover' },
    ],
    protocol: 'Zwift - Recovery',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw17_vo2_ladder',
    title: 'VO2 Ladder',
    category: 'VO2MAX',
    description: 'Ascending VO2max ladder',
    purpose: 'VO2max progression',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'VO2 Ladder', durationPercent: 82, powerLow: 110, powerHigh: 130, zone: 'Z5', rpe: 9, purpose: 'VO2max', coachNote: 'Ascending efforts' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy recovery' },
    ],
    protocol: 'Zwift - VO2 Ladder',
    researcher: 'Zwift Labs',
    structure: 'ladder',
  },

  {
    id: 'zw18_tempo_ladder',
    title: 'Tempo Ladder',
    category: 'TEMPO',
    description: 'Progressive tempo efforts',
    purpose: 'Tempo progression',
    zone: 'Z3-Z4',
    duration: 60,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build up' },
      { name: 'Tempo Ladder', durationPercent: 80, powerLow: 76, powerHigh: 95, zone: 'Z3-Z4', rpe: 6, purpose: 'Tempo', coachNote: 'Progressive tempo efforts' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Tempo Ladder',
    researcher: 'Zwift Labs',
    structure: 'ladder',
  },

  {
    id: 'zw19_mixed_intervals',
    title: 'Mixed Intervals',
    category: 'MIXED',
    description: 'Multi-zone mixed efforts',
    purpose: 'Mixed intensity',
    zone: 'Z2-Z5',
    duration: 60,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Begin' },
      { name: 'Mixed', durationPercent: 80, powerLow: 60, powerHigh: 120, zone: 'Z2-Z5', rpe: 6, purpose: 'Mixed', coachNote: 'Varied intensity work' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Mixed',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  // ─── BUILD ME UP SERIES (36) ────────────────────────────────────
  
  {
    id: 'zw20_calibration',
    title: 'Calibration',
    category: 'BASE',
    description: 'Fitness checkpoint workout',
    purpose: 'Assess fitness',
    zone: 'Z2-Z3',
    duration: 45,
    difficultyScore: 3,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Easy preparation' },
      { name: 'Calibration', durationPercent: 80, powerLow: 65, powerHigh: 85, zone: 'Z2-Z3', rpe: 4, purpose: 'Check fitness', coachNote: 'Gauge current state' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy recovery' },
    ],
    protocol: 'Zwift - Calibration',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  // Unicorn Progression (7 levels) - CORE OF BUILD ME UP
  {
    id: 'zw24_unicorn_red',
    title: 'Unicorn Red',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 1 (Red)',
    purpose: 'Build VO2max',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare for progression' },
      { name: 'Red Unicorn', durationPercent: 80, powerLow: 105, powerHigh: 115, zone: 'Z5', rpe: 7, purpose: 'VO2max', coachNote: 'Entry level VO2 progression' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Unicorn Red',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw25_unicorn_orange',
    title: 'Unicorn Orange',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 2 (Orange)',
    purpose: 'Build VO2max',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Ready for challenge' },
      { name: 'Orange Unicorn', durationPercent: 80, powerLow: 110, powerHigh: 120, zone: 'Z5', rpe: 7, purpose: 'VO2max', coachNote: 'Step up in intensity' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Unicorn Orange',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw26_unicorn_yellow',
    title: 'Unicorn Yellow',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 3 (Yellow)',
    purpose: 'Build VO2max',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare hard' },
      { name: 'Yellow Unicorn', durationPercent: 80, powerLow: 115, powerHigh: 125, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: 'Getting serious now' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recover well' },
    ],
    protocol: 'Zwift - Unicorn Yellow',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw27_unicorn_green',
    title: 'Unicorn Green',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 4 (Green)',
    purpose: 'Peak VO2max',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Thorough preparation' },
      { name: 'Green Unicorn', durationPercent: 80, powerLow: 120, powerHigh: 130, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: 'Significant challenge' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - Unicorn Green',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw28_unicorn_blue',
    title: 'Unicorn Blue',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 5 (Blue)',
    purpose: 'Peak VO2max',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full commitment ahead' },
      { name: 'Blue Unicorn', durationPercent: 80, powerLow: 125, powerHigh: 135, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: 'Elite level intensity' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Allow full recovery' },
    ],
    protocol: 'Zwift - Unicorn Blue',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw29_unicorn_indigo',
    title: 'Unicorn Indigo',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 6 (Indigo)',
    purpose: 'Extreme VO2max',
    zone: 'Z5-Z6',
    duration: 60,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Extended preparation needed' },
      { name: 'Indigo Unicorn', durationPercent: 80, powerLow: 130, powerHigh: 140, zone: 'Z5-Z6', rpe: 9, purpose: 'VO2max', coachNote: 'Extreme VO2 stimulus' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Very full recovery required' },
    ],
    protocol: 'Zwift - Unicorn Indigo',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw30_unicorn_violet',
    title: 'Unicorn Violet',
    category: 'VO2MAX',
    description: 'Unicorn progression - Level 7 (Violet)',
    purpose: 'Maximum VO2max',
    zone: 'Z5-Z6',
    duration: 60,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Maximum prep required' },
      { name: 'Violet Unicorn', durationPercent: 80, powerLow: 135, powerHigh: 145, zone: 'Z5-Z6', rpe: 10, purpose: 'VO2max', coachNote: 'Peak VO2 - near maximum' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete, thorough recovery' },
    ],
    protocol: 'Zwift - Unicorn Violet',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  // Other Build Me Up workouts
  {
    id: 'zw21_90_trifecta_ded',
    title: '90% Trifecta - Devedeset',
    category: 'SWEET_SPOT',
    description: '90% FTP repeats (Devedeset)',
    purpose: 'Sweet spot repeats',
    zone: 'Z3',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: '90% SS', durationPercent: 80, powerLow: 88, powerHigh: 95, zone: 'Z3', rpe: 7, purpose: 'Sweet spot', coachNote: 'At 90% FTP' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - 90% Devedeset',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw22_90_trifecta_half',
    title: '90% Trifecta - Halfems',
    category: 'SWEET_SPOT',
    description: '90% FTP repeats (Halfems)',
    purpose: 'Sweet spot repeats',
    zone: 'Z3',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build up' },
      { name: '90% SS', durationPercent: 80, powerLow: 88, powerHigh: 95, zone: 'Z3', rpe: 7, purpose: 'Sweet spot', coachNote: 'Sustained 90% effort' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - 90% Halfems',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw23_90_trifecta_nov',
    title: '90% Trifecta - Novanta',
    category: 'SWEET_SPOT',
    description: '90% FTP repeats (Novanta)',
    purpose: 'Sweet spot repeats',
    zone: 'Z3',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Ready for effort' },
      { name: '90% SS', durationPercent: 80, powerLow: 88, powerHigh: 95, zone: 'Z3', rpe: 7, purpose: 'Sweet spot', coachNote: 'Hold 90% power' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Finish easy' },
    ],
    protocol: 'Zwift - 90% Novanta',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  // Remaining Build Me Up (abbreviated - adding key ones)
  {
    id: 'zw31_pedal_drill1',
    title: 'Pedaling Drill 1',
    category: 'TECHNIQUE',
    description: 'Smooth pedaling development',
    purpose: 'Pedal efficiency',
    zone: 'Z2',
    duration: 45,
    difficultyScore: 3,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 15, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Easy start' },
      { name: 'Pedaling Drills', durationPercent: 75, powerLow: 55, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Technique', coachNote: 'Focus on smooth pedal stroke' },
      { name: 'Cool-down', durationPercent: 10, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Pedal Drill 1',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw32_pedal_drill2',
    title: 'Pedaling Drill 2',
    category: 'TECHNIQUE',
    description: 'Advanced pedaling efficiency',
    purpose: 'Pedal efficiency',
    zone: 'Z2',
    duration: 45,
    difficultyScore: 4,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 15, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Advanced Drills', durationPercent: 75, powerLow: 60, powerHigh: 80, zone: 'Z2', rpe: 3, purpose: 'Technique', coachNote: 'Precision pedaling work' },
      { name: 'Cool-down', durationPercent: 10, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Pedal Drill 2',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw33_strength1',
    title: 'Strength Tier 1',
    category: 'STRENGTH',
    description: 'Low cadence force work',
    purpose: 'Build strength',
    zone: 'Z2-Z3',
    duration: 45,
    difficultyScore: 5,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Prepare muscles' },
      { name: 'Low Cadence', durationPercent: 80, powerLow: 70, powerHigh: 85, zone: 'Z2-Z3', rpe: 5, purpose: 'Strength', coachNote: '50-60 RPM force work' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy recovery' },
    ],
    protocol: 'Zwift - Strength Tier 1',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw34_strength2',
    title: 'Strength Tier 2',
    category: 'STRENGTH',
    description: 'Heavy resistance strength work',
    purpose: 'Build strength',
    zone: 'Z2-Z3',
    duration: 45,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Full prep' },
      { name: 'Heavy Resistance', durationPercent: 80, powerLow: 75, powerHigh: 90, zone: 'Z2-Z3', rpe: 6, purpose: 'Strength', coachNote: 'Heavy force work' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - Strength Tier 2',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw35_tech1',
    title: 'Tech Work 1',
    category: 'TECHNIQUE',
    description: 'Cadence variation work',
    purpose: 'Pedal versatility',
    zone: 'Z2',
    duration: 45,
    difficultyScore: 4,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Build up' },
      { name: 'Cadence Variation', durationPercent: 80, powerLow: 60, powerHigh: 80, zone: 'Z2', rpe: 3, purpose: 'Technique', coachNote: 'Vary cadence 60-110 RPM' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Tech Work 1',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw36_tech2',
    title: 'Tech Work 2',
    category: 'TECHNIQUE',
    description: 'Skills development work',
    purpose: 'Pedal versatility',
    zone: 'Z2-Z3',
    duration: 50,
    difficultyScore: 5,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Skills Work', durationPercent: 80, powerLow: 65, powerHigh: 85, zone: 'Z2-Z3', rpe: 4, purpose: 'Technique', coachNote: 'Single-leg, power balance work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Tech Work 2',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw37_vo2_method',
    title: 'VO2 Method',
    category: 'VO2MAX',
    description: 'Classic VO2max protocol',
    purpose: 'VO2max development',
    zone: 'Z5',
    duration: 50,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full prep' },
      { name: 'VO2 Repeats', durationPercent: 80, powerLow: 115, powerHigh: 125, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: 'Proven VO2 protocol' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy' },
    ],
    protocol: 'Zwift - VO2 Method',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw38_vo2_tine',
    title: 'VO2 Tine',
    category: 'VO2MAX',
    description: 'VO2max variant',
    purpose: 'VO2max',
    zone: 'Z5',
    duration: 50,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'VO2 Variant', durationPercent: 80, powerLow: 118, powerHigh: 128, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: 'Modified VO2 work' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - VO2 Tine',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw39_vo2_tines',
    title: 'VO2 Tines',
    category: 'VO2MAX',
    description: 'Double VO2max work',
    purpose: 'VO2max power',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Extended prep' },
      { name: 'Double VO2', durationPercent: 80, powerLow: 120, powerHigh: 130, zone: 'Z5', rpe: 9, purpose: 'VO2max', coachNote: 'Advanced VO2 work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Full recovery' },
    ],
    protocol: 'Zwift - VO2 Tines',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw40_vo2_15_9',
    title: 'VO2 15/9',
    category: 'VO2MAX',
    description: '15min VO2 / 9min recovery',
    purpose: 'VO2max capacity',
    zone: 'Z5',
    duration: 60,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare fully' },
      { name: '15/9 VO2', durationPercent: 80, powerLow: 115, powerHigh: 125, zone: 'Z5', rpe: 8, purpose: 'VO2max', coachNote: '15min hard, 9min recovery' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy' },
    ],
    protocol: 'Zwift - VO2 15/9',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw41_vo2_lox',
    title: 'VO2 LOX',
    category: 'VO2MAX',
    description: 'Low oxygen VO2 training',
    purpose: 'VO2max',
    zone: 'Z5',
    duration: 55,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Thorough prep' },
      { name: 'LOX Work', durationPercent: 80, powerLow: 125, powerHigh: 135, zone: 'Z5', rpe: 9, purpose: 'VO2max', coachNote: 'Low oxygen stimulus' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - VO2 LOX',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw42_attack1',
    title: 'Attack 1',
    category: 'ANAEROBIC',
    description: 'Attack drill work',
    purpose: 'Attack drills',
    zone: 'Z4-Z5',
    duration: 45,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Ready to attack' },
      { name: 'Attacks', durationPercent: 80, powerLow: 110, powerHigh: 140, zone: 'Z4-Z5', rpe: 8, purpose: 'Attack', coachNote: 'Short power surges' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Attack 1',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw43_attack2',
    title: 'Attack 2',
    category: 'ANAEROBIC',
    description: 'Advanced attack drills',
    purpose: 'Attack power',
    zone: 'Z5-Z6',
    duration: 45,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full prep' },
      { name: 'Hard Attacks', durationPercent: 80, powerLow: 130, powerHigh: 150, zone: 'Z5-Z6', rpe: 9, purpose: 'Attack', coachNote: 'Aggressive attack drills' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Attack 2',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw44_malevolent',
    title: 'Malevolent',
    category: 'VO2MAX',
    description: 'Difficult VO2max work',
    purpose: 'Extreme VO2',
    zone: 'Z5-Z6',
    duration: 60,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full preparation' },
      { name: 'Malevolent', durationPercent: 82, powerLow: 125, powerHigh: 140, zone: 'Z5-Z6', rpe: 9, purpose: 'VO2max', coachNote: 'Seriously hard VO2 work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery needed' },
    ],
    protocol: 'Zwift - Malevolent',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw45_sweetheart',
    title: 'Sweetheart',
    category: 'SWEET_SPOT',
    description: 'Long sweet spot session',
    purpose: 'Sweet spot endurance',
    zone: 'Z3',
    duration: 90,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build gradually' },
      { name: 'Long SS', durationPercent: 82, powerLow: 88, powerHigh: 93, zone: 'Z3', rpe: 7, purpose: 'SS endurance', coachNote: 'Extended sweet spot' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Sweetheart',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw46_exemplary',
    title: 'Exemplary',
    category: 'MIXED',
    description: 'Mixed intensity workout',
    purpose: 'Mixed intensity',
    zone: 'Z2-Z5',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build up' },
      { name: 'Mixed Work', durationPercent: 80, powerLow: 70, powerHigh: 120, zone: 'Z2-Z5', rpe: 6, purpose: 'Mixed', coachNote: 'Varied intensity training' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Finish easy' },
    ],
    protocol: 'Zwift - Exemplary',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw47_alpha',
    title: 'Alpha',
    category: 'THRESHOLD',
    description: 'Threshold focused work',
    purpose: 'Threshold',
    zone: 'Z4',
    duration: 65,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Threshold', durationPercent: 80, powerLow: 95, powerHigh: 105, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Sustained FTP work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Alpha',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  // ─── FTP BUILDER SERIES (16) ─────────────────────────────────

  {
    id: 'zw48_ftp_foundation',
    title: 'FTP Foundation',
    category: 'BASE',
    description: 'Easy base work',
    purpose: 'Aerobic base',
    zone: 'Z2',
    duration: 45,
    difficultyScore: 2,
    intervals: () => [
      { name: 'Base Spin', durationPercent: 100, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Base', coachNote: 'Light base foundation' },
    ],
    protocol: 'Zwift - FTP Foundation',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw49_ftp_strength',
    title: 'FTP Strength',
    category: 'STRENGTH',
    description: 'Strength focus for FTP builder',
    purpose: 'Build strength',
    zone: 'Z2-Z3',
    duration: 50,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 70, zone: 'Z2', rpe: 2, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Force Work', durationPercent: 80, powerLow: 70, powerHigh: 85, zone: 'Z2-Z3', rpe: 5, purpose: 'Strength', coachNote: 'Low cadence strength' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy' },
    ],
    protocol: 'Zwift - FTP Strength',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw50_tempo_prog1',
    title: 'Tempo Progression 1',
    category: 'TEMPO',
    description: 'Early tempo progression',
    purpose: 'Tempo building',
    zone: 'Z3',
    duration: 50,
    difficultyScore: 5,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build' },
      { name: 'Tempo 1', durationPercent: 80, powerLow: 76, powerHigh: 85, zone: 'Z3', rpe: 5, purpose: 'Tempo', coachNote: 'Early tempo progression' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Tempo Prog 1',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw51_tempo_prog2',
    title: 'Tempo Progression 2',
    category: 'TEMPO',
    description: 'Building tempo progression',
    purpose: 'Tempo building',
    zone: 'Z3',
    duration: 55,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Ready' },
      { name: 'Tempo 2', durationPercent: 80, powerLow: 80, powerHigh: 88, zone: 'Z3', rpe: 6, purpose: 'Tempo', coachNote: 'Sustained tempo build' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Tempo Prog 2',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw52_tempo_prog3',
    title: 'Tempo Progression 3',
    category: 'TEMPO',
    description: 'Advanced tempo progression',
    purpose: 'Tempo building',
    zone: 'Z3',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare fully' },
      { name: 'Tempo 3', durationPercent: 80, powerLow: 84, powerHigh: 92, zone: 'Z3', rpe: 6, purpose: 'Tempo', coachNote: 'Advanced tempo work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - Tempo Prog 3',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw53_hiit_w4',
    title: 'HIIT Week 4',
    category: 'VO2MAX',
    description: 'High-intensity interval training Week 4',
    purpose: 'HIIT VO2max',
    zone: 'Z5',
    duration: 45,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare for HIIT' },
      { name: 'HIIT W4', durationPercent: 80, powerLow: 115, powerHigh: 130, zone: 'Z5', rpe: 8, purpose: 'HIIT', coachNote: 'Week 4 HIIT protocol' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy' },
    ],
    protocol: 'Zwift - HIIT W4',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw54_hiit_w6',
    title: 'HIIT Week 6',
    category: 'VO2MAX',
    description: 'High-intensity interval training Week 6',
    purpose: 'HIIT VO2max',
    zone: 'Z5',
    duration: 50,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full prep' },
      { name: 'HIIT W6', durationPercent: 80, powerLow: 120, powerHigh: 135, zone: 'Z5', rpe: 8, purpose: 'HIIT', coachNote: 'Week 6 HIIT protocol' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - HIIT W6',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw55_hiit_w8',
    title: 'HIIT Week 8',
    category: 'VO2MAX',
    description: 'High-intensity interval training Week 8',
    purpose: 'HIIT VO2max',
    zone: 'Z5-Z6',
    duration: 55,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Extended prep' },
      { name: 'HIIT W8', durationPercent: 80, powerLow: 125, powerHigh: 140, zone: 'Z5-Z6', rpe: 9, purpose: 'HIIT', coachNote: 'Peak Week 8 HIIT' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Full recovery' },
    ],
    protocol: 'Zwift - HIIT W8',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw56_threshold_a',
    title: 'Threshold A',
    category: 'THRESHOLD',
    description: 'Threshold progression step A',
    purpose: 'Threshold building',
    zone: 'Z4',
    duration: 55,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Threshold A', durationPercent: 80, powerLow: 92, powerHigh: 100, zone: 'Z4', rpe: 7, purpose: 'Threshold', coachNote: 'Step A threshold work' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy' },
    ],
    protocol: 'Zwift - Threshold A',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw57_threshold_b',
    title: 'Threshold B',
    category: 'THRESHOLD',
    description: 'Threshold progression step B',
    purpose: 'Threshold building',
    zone: 'Z4',
    duration: 60,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Build' },
      { name: 'Threshold B', durationPercent: 80, powerLow: 94, powerHigh: 102, zone: 'Z4', rpe: 7, purpose: 'Threshold', coachNote: 'Step B threshold' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Threshold B',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw58_threshold_c',
    title: 'Threshold C',
    category: 'THRESHOLD',
    description: 'Threshold progression step C',
    purpose: 'Threshold building',
    zone: 'Z4',
    duration: 65,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Ready' },
      { name: 'Threshold C', durationPercent: 80, powerLow: 96, powerHigh: 104, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Step C threshold work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - Threshold C',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw59_threshold_d',
    title: 'Threshold D',
    category: 'THRESHOLD',
    description: 'Threshold progression step D',
    purpose: 'Threshold building',
    zone: 'Z4',
    duration: 65,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 12, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full prep' },
      { name: 'Threshold D', durationPercent: 80, powerLow: 98, powerHigh: 106, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Advanced step D' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Threshold D',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw60_threshold_e',
    title: 'Threshold E',
    category: 'THRESHOLD',
    description: 'Threshold progression step E',
    purpose: 'Threshold building',
    zone: 'Z4',
    duration: 70,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 11, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare' },
      { name: 'Threshold E', durationPercent: 81, powerLow: 100, powerHigh: 108, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Step E threshold work' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Full recovery' },
    ],
    protocol: 'Zwift - Threshold E',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw61_threshold_f',
    title: 'Threshold F',
    category: 'THRESHOLD',
    description: 'Threshold progression step F',
    purpose: 'Threshold building',
    zone: 'Z4',
    duration: 70,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 11, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Extended prep' },
      { name: 'Threshold F', durationPercent: 81, powerLow: 102, powerHigh: 110, zone: 'Z4', rpe: 8, purpose: 'Threshold', coachNote: 'Peak step F threshold' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - Threshold F',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw62_free_ride',
    title: 'Free Ride',
    category: 'MIXED',
    description: 'Unstructured free ride',
    purpose: 'Flexible training',
    zone: 'Z1-Z6',
    duration: 60,
    difficultyScore: 1,
    intervals: () => [
      { name: 'Free Ride', durationPercent: 100, powerLow: 30, powerHigh: 200, zone: 'Z1-Z6', rpe: 3, purpose: 'Free', coachNote: 'No structure - ride your way' },
    ],
    protocol: 'Zwift - Free Ride',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  // ─── CRIT CRUSHER SERIES (6) ────────────────────────────────

  {
    id: 'zw63_works',
    title: 'The Works',
    category: 'RACE_SIM',
    description: 'Full race simulation',
    purpose: 'Race simulation',
    zone: 'Z1-Z6',
    duration: 75,
    difficultyScore: 9,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 10, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full prep for race sim' },
      { name: 'Race Sim', durationPercent: 82, powerLow: 70, powerHigh: 150, zone: 'Z1-Z6', rpe: 8, purpose: 'Race', coachNote: 'Complete race simulation' },
      { name: 'Cool-down', durationPercent: 8, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Full recovery' },
    ],
    protocol: 'Zwift - The Works',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw64_crit_foundation',
    title: 'Crit Foundation',
    category: 'SPRINT',
    description: 'Sprint foundation work',
    purpose: 'Sprint base',
    zone: 'Z2-Z4',
    duration: 45,
    difficultyScore: 5,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare for sprints' },
      { name: 'Sprint Base', durationPercent: 80, powerLow: 80, powerHigh: 110, zone: 'Z2-Z4', rpe: 6, purpose: 'Sprint base', coachNote: 'Build sprint capacity' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy' },
    ],
    protocol: 'Zwift - Crit Foundation',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw65_split_session',
    title: 'Split Session',
    category: 'MIXED',
    description: 'Two-part workout session',
    purpose: 'Mixed efforts',
    zone: 'Z2-Z5',
    duration: 60,
    difficultyScore: 6,
    intervals: () => [
      { name: 'Part 1', durationPercent: 40, powerLow: 70, powerHigh: 90, zone: 'Z3', rpe: 5, purpose: 'Build', coachNote: 'First part of split' },
      { name: 'Rest', durationPercent: 10, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Recovery', coachNote: 'Rest between parts' },
      { name: 'Part 2', durationPercent: 40, powerLow: 110, powerHigh: 130, zone: 'Z5', rpe: 8, purpose: 'Hard', coachNote: 'Second hard part' },
      { name: 'Cool-down', durationPercent: 10, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy finish' },
    ],
    protocol: 'Zwift - Split Session',
    researcher: 'Zwift Labs',
    structure: 'mixed',
  },

  {
    id: 'zw66_crit_strength',
    title: 'Crit Strength',
    category: 'STRENGTH',
    description: 'Sprint strength work',
    purpose: 'Sprint strength',
    zone: 'Z2-Z3',
    duration: 50,
    difficultyScore: 7,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Prepare muscles' },
      { name: 'Strength', durationPercent: 80, powerLow: 85, powerHigh: 100, zone: 'Z2-Z3', rpe: 7, purpose: 'Strength', coachNote: 'Sprint strength building' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Recovery' },
    ],
    protocol: 'Zwift - Crit Strength',
    researcher: 'Zwift Labs',
    structure: 'steady',
  },

  {
    id: 'zw67_microbursts_crit',
    title: 'Crit Microbursts',
    category: 'ANAEROBIC',
    description: 'Race-like attack bursts',
    purpose: 'Race attacks',
    zone: 'Z4-Z6',
    duration: 50,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Full prep' },
      { name: 'Attacks', durationPercent: 80, powerLow: 120, powerHigh: 160, zone: 'Z4-Z6', rpe: 8, purpose: 'Attack', coachNote: 'Crit-race style attacks' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Easy out' },
    ],
    protocol: 'Zwift - Crit Microbursts',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },

  {
    id: 'zw68_30_30_anaerobic',
    title: '30/30 Anaerobic',
    category: 'ANAEROBIC',
    description: 'Anaerobic 30/30 repeats',
    purpose: 'Anaerobic power',
    zone: 'Z5-Z6',
    duration: 45,
    difficultyScore: 8,
    intervals: () => [
      { name: 'Warm-up', durationPercent: 13, powerLow: 50, powerHigh: 75, zone: 'Z2', rpe: 3, purpose: 'Warm up', coachNote: 'Thorough prep' },
      { name: '30/30', durationPercent: 80, powerLow: 140, powerHigh: 160, zone: 'Z5-Z6', rpe: 9, purpose: 'Anaerobic', coachNote: '30s hard, 30s easy repeats' },
      { name: 'Cool-down', durationPercent: 7, powerLow: 40, powerHigh: 60, zone: 'Z1', rpe: 1, purpose: 'Cool down', coachNote: 'Complete recovery' },
    ],
    protocol: 'Zwift - 30/30 Anaerobic',
    researcher: 'Zwift Labs',
    structure: 'repeats',
  },
];

export const ZWIFT_COUNT = ZWIFT_WORKOUTS.length;
